acme_store:
    resource: "@AcmeStoreBundle/Controller/"
    type:     annotation
    prefix:   /

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"